version: '3.7'

services:
  web:
    image: goapp-rest-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - "database"

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'goapp-rest-api'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'niveus@123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
    my-db:
      